;===========================================================
; PlatformIO Configuration
; Home Security Hub
; ESP8266 NodeMCU v2
;===========================================================

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

;-----------------------------------------------------------
; Serial Monitor
;-----------------------------------------------------------

monitor_speed = 115200
monitor_filters = esp8266_exception_decoder

;-----------------------------------------------------------
; Upload
;-----------------------------------------------------------

upload_speed = 921600

;-----------------------------------------------------------
; Build
;-----------------------------------------------------------

build_type = release

build_flags =
   ; -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
   ; -D BEARSSL_SSL_BASIC
    -Wall
    -Wextra

;-----------------------------------------------------------
; Libraries
;-----------------------------------------------------------

lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.4.2

;-----------------------------------------------------------
; Filesystem (Optional)
;-----------------------------------------------------------

board_build.filesystem = littlefs